### ISSUE TITLE
Unexpected error: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by tomybyte** [ldziedziul/matterbook#3] opened 2017-01-05 13:24 UTC
Hi,

after running matterbook-run.sh the script loops endless on the first integration's entry.

Any suggestion for me?

Sincerely

matterbook.yml
```
integrations:
- wisstihrnochde:
    fb_page_id: wisstihrnochde
    mm_icon_url: https://scontent.ftxl1-1.fna.fbcdn.net/v/t1.0-1/13179177_228654837513360_1057215643641624075_n.png?oh=8f73d4954ca3c4c8fc8016dc40c74d17&oe=5918BC5A
- boredpanda:
    fb_page_id: boredpanda
    mm_icon_url: https://scontent.ftxl1-1.fna.fbcdn.net/v/t1.0-1/312614_10150468492209252_2128535989_n.jpg?oh=50e49b81792a2dfdf84724eddea42c0d&oe=591E595D
- die90er:
    fb_page_id: die90er
    mm_icon_url: https://scontent.ftxl1-1.fna.fbcdn.net/v/t1.0-1/12794573_10153566322040939_2285120631744213202_n.png?oh=0ccec9446e165467f145ce935799ff0a&oe=58EC0BDE
```
```
./matterbook-run.sh
2017-01-05 14:22:37,689 [matterbook] Matterbook started
2017-01-05 14:22:37,689 [matterbook] Press Ctrl+C or send SIGINT to exit
2017-01-05 14:22:37,855 [matterbook] Checking: wisstihrnochde
2017-01-05 14:22:38,032 [matterbook] Unexpected error: 'NoneType' object has no attribute 'encode'
2017-01-05 14:22:48,042 [matterbook] Checking: wisstihrnochde
2017-01-05 14:22:48,212 [matterbook] Unexpected error: 'NoneType' object has no attribute 'encode'

```

**Comment by ldziedziul** [comment] 2017-01-05 14:14
The cause was empty fb_post_filter. I've pushed the fix to accept such configurations.

**Closed as completed by ldziedziul** 2017-01-05 14:14 UTC
Labels: bug

**Comment by tomybyte** [comment] 2017-01-05 14:26
works fine now!

Thanks a lot!
